request version <= 2.81.0 to try to fix SyntaxError const Hoek
to try to solve problem with: const Hoek = require('hoek');
SyntaxError: Use of const in strict mode.